Lesson 2, movie 3, 4min3sec - I cannot compile my first test :-(
Information:java: Errors occurred while compiling module 'sandbox_test'
Information:javac 1.8.0_121 was used to compile java sources
Information:2017-03-29 23:48 - Compilation completed with 2 errors and 0
warnings in 2s 289ms

C:\Devel\java_pft\sandbox\src\test\java\ru\stqa\pft\sandox\SquareTests.java
Error:(13, 5) java: cannot find symbol
symbol:   class Square
location: class ru.stqa.pft.sandox.SquareTests
Error:(13, 20) java: cannot find symbol
symbol:   class Square
location: class ru.stqa.pft.sandox.SquareTests